Honeytrap starting (d1uigpi9eed00086kjng)...
Version: DEVELOPMENT.GOGET (DEVELOPMENT.)
[36m17:33:26.841 honeytrap/server â–¶ DEBU 002 Using datadir: /data[0m
[36m17:33:26.842 services â–¶ DEBU 003 Could not load private-key, generating one.[0m
17:33:27.256 honeytrap/server â–¶ INFO 004 Configured service ssh-simulator (ssh-simulator)[0m
17:33:27.256 honeytrap/server â–¶ INFO 005 Configured service telnet (telnet)[0m
17:33:27.256 honeytrap/server â–¶ INFO 006 Configured port tcp/:8022[0m
17:33:27.256 honeytrap/server â–¶ INFO 007 Configured port tcp/:8023[0m
17:33:27.256 honeytrap/server â–¶ INFO 008 Configured port tcp/:5900[0m
[33m17:33:27.257 honeytrap/server â–¶ WARN 009 Unrecognized keys in configuration: [service.telnet.image service.telnet.server-name][0m
17:33:27.257 listeners/socket â–¶ INFO 00a Listener started: tcp/:8022[0m
17:33:27.257 listeners/socket â–¶ INFO 00b Listener started: tcp/:8023[0m
17:33:27.257 listeners/socket â–¶ INFO 00c Listener started: tcp/:5900[0m
honeytrap > heartbeat > category=heartbeat, date=2025-07-20 17:33:56.875423072 +0000 UTC m=+30.286975287, sensor=honeytrap, sequence=0, token=d1uigpi9eed00086kjng, type=info
Honeytrap stopped.
